kind: ConfigMap
apiVersion: v1
metadata:
  name: greetings-config
data:
  application.yml: |-
    dialog:
      greeting: Say Hello to the World
      farewell: Say Goodbye
    ---
    spring:
      profiles: development
    dialog:
      greeting: Say Hello to the Developers
      farewell: Say Goodbye to the Developers
    ---
    spring:
      profiles: production
    dialog:
      greeting: Say Hello to the Ops Team
      farewell: Say Goodbye to the Ops Team
