AWS_ACCESS_KEY_ID: ${aws_secret_key_id}
AWS_SECRET_ACCESS_KEY: ${aws_secret_access_key}
AWS_REGION: ${aws_region}
AWS_NODE_AZ: ${aws_node_az}
AWS_NODE_AZ_1: ${aws_node_az_1}
AWS_NODE_AZ_2: ${aws_node_az_2}
AWS_PRIVATE_NODE_CIDR: ${aws_private_node_cidr}
AWS_PRIVATE_NODE_CIDR_1: ${aws_private_node_cidr_1}
AWS_PRIVATE_NODE_CIDR_2: ${aws_private_node_cidr_2}
AWS_PUBLIC_NODE_CIDR: ${aws_public_node_cidr}
AWS_PUBLIC_NODE_CIDR_1: ${aws_public_node_cidr_1}
AWS_PUBLIC_NODE_CIDR_2: ${aws_public_node_cidr_2}
AWS_SSH_KEY_NAME: ${aws_ssh_key_name}
AWS_VPC_CIDR: ${aws_vpc_cidr}
SERVICE_CIDR: ${service_cidr}
CLUSTER_CIDR: ${cluster_cidr}
CONTROL_PLANE_MACHINE_TYPE: ${control_plane_machine_type}
NODE_MACHINE_TYPE: ${node_machine_type}
