apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: github.com/cloudfoundry/cf-for-k8s
    git:
      url: https://github.com/cloudfoundry/cf-for-k8s
      ref: 53ef15e87eb0021cfd04bd7c15944471c7e1d55f
    includePaths:
    - config/**/*
    - hack/**/*
