apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: harbor-cert
  namespace: ${namespace}
spec:
  dnsNames:
  - '${harbor_domain}'
  - '${notary_domain}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: harbor-tls-secret